spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userDataDb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: USER-SERVICE

jwt:
  secret:
    key: zq8ErKjjaUqOJWqFr7ZBQQk70KgB3sUSKdwJ4y58iO3Gjr91TZHhyjNhEBkVKzM
  expiration: 900000
logging:
  level:
    org.springframework.security: DEBUG
key:
  bytes: "2,-1,-100,39,88,-56,96,75,2,85,86,26,28,-100,8,84"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}