spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userDataDb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: userService

jwt:
  secret:
    key: zq8ErKjjaUqOJWqFr7ZBQQk70KgB3sUSKdwJ4y58iO3Gjr91TZHhyjNhEBkVKzM
  expiration: 900000
logging:
  level:
    org.springframework.security: DEBUG