spring:
  application:
    name: NOTIFICATION-SERVICE
  kafka:
    bootstrap-servers: https://kind-bedbug-5770-us1-kafka.upstash.io:9092
    username: a2luZC1iZWRidWctNTc3MCQOtjI3Pp7DrGRlN4dSECG_7WL_eZCyzJ_pFsZzF2A
    password: ZWYwZTlmOWUtYjkyYy00YzFkLTlkMDMtYzNmYjhjZTU0ODFl
    consumer:
      group-id: emp-email-group
server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}